# Generated by Django 3.2 on 2021-04-26 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Qusetion',
            new_name='Question',
        ),
    ]
